# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29cb7153c56f670a43edb7a1bb1ed07a36f63a111eba9140bff354a5dc501577f8464a8b8cc8ecbdc16fbaeedc0ad35ee7b0ef661e99d210c999ad569f9c9e97

test:
  secret_key_base: 9ced1a3ca19814c3856f25e83c156bc7070e0041c05665dc9cdec554e7ef2009e51acce8d5fb0dd0fdf1a411e2491185a9b5c9132383e7f4eeecd52c6a5440c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
